# Example configuration file for ansible-lint
skip_list:
  - experimental  # Skip experimental rules
  - role-name  # Example of skipping a specific rule
verbosity: 1  # Control output verbosity
exclude_paths:
  - docs/  # Example of directories to exclude
  - tests/
